/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cccat;

import picocli.CommandLine;

public class App{
    public static void main(String[] args) {
        int exitCode = new CommandLine(new CatClass()).execute(args);
        System.exit(exitCode);
    }
}
